### ISSUE TITLE
Create daily GHA script to update to latest GNDB database

### ISSUE THREAD

**Issue by ronaldtse** [interscript/geonames-transliteration-data#5]
This task is to create a daily GHA script that runs the "release" workflow daily in order to publish the latest database extract.

The release number should be the version of the GNDB of the downloaded database.

**Comment by ronaldtse** [comment]
At this link: https://geonames.nga.mil/gns/html/namefiles.html

There is this line that indicates the last updated date.
<img width="728" alt="Screenshot 2021-06-23 at 3 28 45 PM" src="https://user-images.githubusercontent.com/11865/123054735-baf76f80-d437-11eb-9c51-b3b675556ae4.png">

We want to publish a new release whenever this gets updated. We just need to check daily.

**Comment by ronaldtse** [comment]
We can use:
* a cron trigger 
* check if tag exists: https://github.com/marketplace/actions/tag-exists-action
* condition to check if the tag already exists: https://github.community/t/avoid-double-builds-when-reacting-on-conditional-tag-event/16656

**Comment by ronaldtse** [comment]
@CAMOBAP is now working on this, thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse could you please give me write permissions.

BTW here Is my workflow

```
name: check_update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_update:
    name: Check updates on https://geonames.nga.mil/gns/html/namefiles.html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.INTERSCRIPT_CI_PAT }}

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install sqlite3 curl make

      - name: Fetch GeoNames last version
        run: |
          make data/VERSION
          echo "GNS_VERSION=v$(cat data/VERSION)" >> $GITHUB_ENV
      
      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with: 
          tag: ${{ env.GNS_VERSION }}

      - if: ${{ !steps.checkTag.outputs.exists }}
        run: |
          git config user.name "interscript-ci"
          git config user.email "interscript-ci@users.noreply.github.com"
          git tag ${{ env.GNS_VERSION }}
          git push origin master --tags


```

1. BTW should we do some make targets before tag something or just tag?
